# Generated by Django 6.0.2 on 2026-02-23 20:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeocodeCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('provider', models.CharField(default='nominatim', max_length=50)),
                ('lat_rounded', models.DecimalField(db_index=True, decimal_places=4, max_digits=9)),
                ('lon_rounded', models.DecimalField(db_index=True, decimal_places=4, max_digits=9)),
                ('state', models.CharField(max_length=100)),
                ('county', models.CharField(max_length=100)),
                ('locality', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_response', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'geocode_cache',
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('total_rows', models.IntegerField(default=0)),
                ('processed_rows', models.IntegerField(default=0)),
                ('success_rows', models.IntegerField(default=0)),
                ('failed_rows', models.IntegerField(default=0)),
                ('error_report', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'import_job',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order_timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('geo_state', models.CharField(max_length=100)),
                ('geo_county', models.CharField(max_length=100)),
                ('geo_locality', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_source', models.CharField(max_length=50)),
                ('geo_raw_response', models.JSONField()),
                ('composite_rate', models.DecimalField(decimal_places=4, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('jurisdictions', models.JSONField()),
                ('breakdown', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='TaxRateAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(db_index=True, max_length=50)),
                ('county', models.CharField(db_index=True, max_length=100)),
                ('locality', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('rate_state', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rate_county', models.DecimalField(decimal_places=4, max_digits=6)),
                ('rate_locality', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('rate_special', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tax_rate_admin',
                'indexes': [models.Index(fields=['state', 'county', 'locality', 'valid_from', 'valid_to'], name='tax_rate_ad_state_e6238d_idx')],
            },
        ),
    ]
